### ISSUE TITLE
Support for virtual media over IPMI?

### ISSUE THREAD

**Issue by ringods** [lindenbaum/eipmi#4]
Hello,

In IPMI v2.0, one of the supported features seems to be "virtual media", the ability to mount remote floppy, CD-ROM and USB. If I search the spec, these words don't even pop up. There is not a lot of information to be found how virtual media is implemented over IPMI. I suspect it is a specific payload type.

Two questions:
* is virtual media somewhere standardised or is this an OEM specific payload type?
* do you know of any information on the net about the the protocol for virtual media? (I have a SuperMicro board)

Let's discuss.

**Comment by schlagert** [comment]
Hi,

since this isn't mentioned in the official Intel documentation I'm pretty sure that this is an OEM specific command/extension. We developed `eipmi` to support our use-case primarily (which is IPMI v1.5 along with MicroTCA/PICMG specific extensions) so I don't have much information on other OEM specific implementations.

Scanning through the documentation on the (SuperMicro)[http://www.supermicro.com/solutions/IPMI.cfm] site does not reveal any command specifications (only end-user GUI documentation). That makes me guess the only supported way is using that GUI tooling.

However, there seems to be some kind of command line tool they ship along with their products called `SMCIPMITool`. Since it is licensed under `GPL` I assume that it is (IPMItool)[http://sourceforge.net/projects/ipmitool/] under the hood. The license should force them to contribute patches back to the original, which leaves the possibility that you can find some command specifications in the `IPMItool` source code.

If that all doesn't help you could finally try and have a direct look using `tcpdump` or `wireshark`. The latter one has some good support to view the IPMI message fundamentals (Command, NetFn,...).

Let me know what you think.

**Comment by schlagert** [comment]
@ringods Do you require further assistance? Otherwise, I would like to close this issue.

**Comment by ringods** [comment]
@schlagert you can close for now. I'm short on time to implement this.
