### ISSUE TITLE
support for sol activate/deactivate

### ISSUE THREAD

**Issue by mirceal** [lindenbaum/eipmi#6]
If understand this correctly, currently there is no support for serial over lan (activation/deactivation).
Is that something that you would considered adding?

**Comment by mirceal** [comment]
looking at: https://sourceforge.net/p/ipmitool/source/ci/master/tree/lib/ipmi_sol.c it seems that it's more than just issuing the activate/deactivate. It's actually activating and after that entering a loop where it listens/translates traffic coming from/going to the BMC

**Comment by schlagert** [comment]
First of all, sorry for the late answer.

Currently, we have no plans to add this (ourselves). Since we need to communicate with ATCA/µTCA equipment the LAN interface is our primary focus. But we encourage everyone else to add SOL support, as long as it does not break the LAN interface ;-)

Looking at the latest [Spec](http://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/ipmi-intelligent-platform-mgt-interface-spec-2nd-gen-v2-0-spec-update.pdf) I see that SOL is an addition of IPMI 2.0. In order to support it, one would have to implement the RMCP+ extension and additionally the SOL Protocol (ACK/NACK)... at least.

I'm here to help if any questions arise.

Regards
Tobias

**Comment by mirceal** [comment]
I did take a quick look at what you're doing internally and at what ipmitool is doing internally. Doesn't look like it would be very hard to implement, but I would not say it's trivial. will take a more in-depth look and will touch base with you if i decide to go ahead and implement it.

**Comment by schlagert** [comment]
Ok, I think support for this extension will not happen in the near future.
